PetComes/server

src/main/java/com/pet/comes/PetcomesApplication.java
src/main/java/com/pet/comes/dto/Join/UserJoinDto.java
src/main/java/com/pet/comes/dto/Req/DiaryReqDto.java
src/main/java/com/pet/comes/dto/Req/PetReqDto.java
src/main/java/com/pet/comes/model/Entity/ActivatedBadge.java
src/main/java/com/pet/comes/model/Entity/Addiction.java
src/main/java/com/pet/comes/model/Entity/Badge.java
src/main/java/com/pet/comes/model/Entity/Breed.java
src/main/java/com/pet/comes/model/Entity/Comment.java
src/main/java/com/pet/comes/model/Entity/Diary.java
src/main/java/com/pet/comes/model/Entity/Dog.java
src/main/java/com/pet/comes/model/Entity/Family.java
src/main/java/com/pet/comes/model/Entity/Icon.java
src/main/java/com/pet/comes/model/Entity/Notification.java
src/main/java/com/pet/comes/model/Entity/Pin.java
src/main/java/com/pet/comes/model/Entity/Schedule.java
src/main/java/com/pet/comes/model/Entity/User.java
src/main/java/com/pet/comes/model/Entity/WithDogs.java
src/main/java/com/pet/comes/model/Entity/address.java
src/main/java/com/pet/comes/model/EnumType/DogStatus.java
src/main/java/com/pet/comes/model/EnumType/SexType.java
src/main/java/com/pet/comes/model/EnumType/SocialType.java
src/main/java/com/pet/comes/model/EnumType/UserStatus.java
src/main/java/com/pet/comes/model/EnumType/WeightType.java
src/main/java/com/pet/comes/model/Timestamped.java
src/main/java/com/pet/comes/repository/DogRepository.java
src/main/java/com/pet/comes/repository/UserRepository.java
src/main/resources/application.properties

application.properties 수정

---

src/main/java/com/pet/comes/controller/UserController.java
src/main/java/com/pet/comes/model/Entity/Dog.java
src/main/java/com/pet/comes/model/Entity/Family.java
src/main/java/com/pet/comes/model/Entity/User.java
src/main/java/com/pet/comes/repository/UserRepository.java
src/main/java/com/pet/comes/service/DogService.java
src/main/java/com/pet/comes/service/UserService.java
src/main/resources/application.yml

강아지 등록API  Family 생성시 해당 user에게 family가 있는지 확인하는 코드 추가 ( Family 중복 방지 )

홈-상단부-1 [H4] 강아지 등록 API - Tony1

---

src/main/java/com/pet/comes/controller/UserController.java
src/main/java/com/pet/comes/dto/MyFamilyDto.java
src/main/java/com/pet/comes/repository/UserRepository.java
src/main/java/com/pet/comes/service/FamilyService.java
src/main/java/com/pet/comes/service/UserService.java
src/main/resources/application.yml

가족 계정 등록 API 아직이라서 임의로 family_id 공유하게끔 데이터베이스 설정

홈-상단부-1 [H7] GET 내 가족 목록 조회API 

---

src/main/java/com/pet/comes/model/Entity/Comment.java
src/main/java/com/pet/comes/repository/CommentRepository.java

DB 수정
comment_id 새롭게 만들고 pk로 수정
- > user_id 가 같은 댓글의 경우 하나만 계속 수정되는 현상으로 인하여 수정

홈-하단부-1 [D8] POST 다이어리 댓글 작성 API- DB수정

---

src/main/java/com/pet/comes/controller/CommentController.java
src/main/java/com/pet/comes/dto/Rep/CommentListRepDto.java
src/main/java/com/pet/comes/dto/Rep/CommentWriteRepDto.java
src/main/java/com/pet/comes/dto/Rep/DiaryListRepDto.java
src/main/java/com/pet/comes/dto/Req/CommentReqDto.java
src/main/java/com/pet/comes/model/Entity/Comment.java
src/main/java/com/pet/comes/repository/CommentRepository.java
src/main/java/com/pet/comes/response/ResponseMessage.java
src/main/java/com/pet/comes/response/Status.java
src/main/java/com/pet/comes/service/CommentService.java
src/main/java/com/pet/comes/service/UserService.java

대댓글 기능을 위한 comment_comment_id 추가

홈-상단부-1 [D8] POST 다이어리 댓글 작성 API + 대댓글기능 추가,comment 테이블 수정

---

src/main/java/com/pet/comes/controller/CommentController.java
src/main/java/com/pet/comes/dto/Rep/MyAccountRepDto.java
src/main/java/com/pet/comes/model/Entity/Comment.java
src/main/java/com/pet/comes/model/Entity/Dog.java
src/main/java/com/pet/comes/model/Entity/Family.java
src/main/java/com/pet/comes/model/Entity/Pin.java
src/main/java/com/pet/comes/service/CommentService.java
src/main/java/com/pet/comes/service/UserService.java

기존의 return 해주는 dto 의 familyId를 List<String> 강아지 이름들을 보내도록 수정하였음.

홈-상단부-1 [H1] GET  내 계정정보 조회 API 수정

---

src/main/java/com/pet/comes/model/Entity/Diary.java
src/main/java/com/pet/comes/model/Entity/User.java
src/main/java/com/pet/comes/service/DiaryService.java

유효성 검사 및 user <-> diary 다대일 양방향 매핑 연관관계 추가

[D2] POST 다이어리 작성 API 유효성 검사 및 user <-> diary 다대일 양방향 매핑 연관관계 추가

---

src/main/java/com/pet/comes/config/securiy/JwtAuthenticationFilter.java
src/main/java/com/pet/comes/config/securiy/JwtTokenProvider.java
src/main/java/com/pet/comes/config/securiy/SecurityConfiguration.java
src/main/java/com/pet/comes/controller/UserController.java

[U1] [U11] 회원가입 일반 로그인 Jwt 기반 API : refresh token 필요함

---

src/main/java/com/pet/comes/controller/DogController.java
src/main/java/com/pet/comes/controller/UserController.java
src/main/java/com/pet/comes/dto/Rep/DogProfileRepDto.java
src/main/java/com/pet/comes/dto/Rep/MyAccountRepDto.java
src/main/java/com/pet/comes/dto/Req/DogReqDto.java
src/main/java/com/pet/comes/model/Entity/Dog.java
src/main/java/com/pet/comes/service/DogService.java
src/main/java/com/pet/comes/service/UserService.java

주석 달기 및 [H1]내 계정정보 조회 , [H4] 강아지 등록 API 점검 및 수정

---

src/main/java/com/pet/comes/controller/CommentController.java
src/main/java/com/pet/comes/controller/UserController.java
src/main/java/com/pet/comes/dto/Rep/UserProfileRepDto.java
src/main/java/com/pet/comes/model/Entity/ActivatedBadge.java
src/main/java/com/pet/comes/model/Entity/Badge.java
src/main/java/com/pet/comes/repository/DiaryRepository.java
src/main/java/com/pet/comes/service/CommentService.java
src/main/java/com/pet/comes/service/DiaryService.java
src/main/java/com/pet/comes/service/UserService.java

뱃지 , 뱃지 액티브 테이블 좀 이해안감. 그리고 좀 수정했음.

[S10] 계정 프로필 조회 API 작성중에 있음 : 뱃지와 연관관계 마무리하기

---

src/main/java/com/pet/comes/service/DiaryService.java

핀 설정/해제시 해당 다이어리에 howManyPins 칼럼 변화하게 수정

[S9] 다이어리 핀 설정하기/해제하기 API 수정

---

src/main/java/com/pet/comes/config/securiy/SecurityConfiguration.java

Spring Security configure 변경 : 모든 요청 허용

---

src/main/java/com/pet/comes/controller/CommentController.java
src/main/java/com/pet/comes/controller/DiaryController.java
src/main/java/com/pet/comes/controller/DogController.java
src/main/java/com/pet/comes/controller/SignController.java
src/main/java/com/pet/comes/controller/UserController.java
src/main/java/com/pet/comes/model/Entity/Address.java
src/main/java/com/pet/comes/model/Entity/Alarm.java
src/main/java/com/pet/comes/repository/AlarmRepository.java
src/main/java/com/pet/comes/service/CommentService.java
src/main/java/com/pet/comes/service/CustomUserDetailService.java
src/main/java/com/pet/comes/service/DiaryService.java
src/main/java/com/pet/comes/service/DogService.java
src/main/java/com/pet/comes/service/FamilyService.java
src/main/java/com/pet/comes/service/UserService.java

[D8] 다이어리 댓글 작성 API 수정

---

src/main/java/com/pet/comes/model/Entity/Pin.java
src/main/java/com/pet/comes/repository/AlarmRepository.java
src/main/java/com/pet/comes/service/CommentService.java
src/main/java/com/pet/comes/service/DiaryService.java
src/main/resources/application.yml

[S9] 다이어리 핀 설정/해체 [S8] 다이어리에 댓글달기 API 수정

---

src/main/java/com/pet/comes/controller/CommentController.java
src/main/java/com/pet/comes/controller/DiaryController.java
src/main/java/com/pet/comes/controller/UserController.java
src/main/java/com/pet/comes/repository/AlarmRepository.java
src/main/java/com/pet/comes/response/ResponseMessage.java
src/main/java/com/pet/comes/response/Status.java
src/main/java/com/pet/comes/service/CommentService.java
src/main/java/com/pet/comes/service/DiaryService.java
src/main/java/com/pet/comes/service/UserService.java

[H2] 읽지 않은 알림 개수 조회API

---

src/main/java/com/pet/comes/repository/UserRepository.java
src/main/java/com/pet/comes/service/DogService.java

findByUserId 삭제 
- > findById 기본 메소드 사용가능함.

[A2] 동물등록번호 조회 API UserRepository 기본 메소드명에 위배된 사항 수정

---

src/main/java/com/pet/comes/controller/DogController.java
src/main/java/com/pet/comes/dto/Req/AnimalRegistrationReqDto.java
src/main/java/com/pet/comes/dto/Req/DogBodyInformationDto.java
src/main/java/com/pet/comes/dto/Req/DogReqDto.java
src/main/java/com/pet/comes/model/Entity/Dog.java
src/main/java/com/pet/comes/model/Entity/DogLog.java
src/main/java/com/pet/comes/model/Entity/DogLogId.java
src/main/java/com/pet/comes/repository/DogLogRepository.java
src/main/java/com/pet/comes/response/ResponseMessage.java
src/main/java/com/pet/comes/response/Status.java
src/main/java/com/pet/comes/service/DogService.java
src/main/java/com/pet/comes/util/openAPI/AnimalRegNoValidateService.java
src/main/resources/application-openAPI.yml

DogLog 관련 Entity 매핑 이슈 해결 
-> 기본키가 왜래키일때 복합키로 취급(?)하여 직렬화 해줬음.

Forkheatherbranch

---

src/main/java/com/pet/comes/controller/DiaryController.java
src/main/java/com/pet/comes/dto/Rep/DiaryListRepDto.java
src/main/java/com/pet/comes/dto/Req/DiaryReqDto.java
src/main/java/com/pet/comes/service/DiaryService.java
src/main/resources/application.yml

[D1]: 유저에 따라 공개/비공개 유무 , [D2]: userId에대한 유효성 검사

[D1] 강아지별 다이어리 조회(홈) , [D2] 다이어리 작성 API 수정

---

src/main/java/com/pet/comes/controller/CommentController.java
src/main/java/com/pet/comes/controller/DiaryController.java
src/main/java/com/pet/comes/repository/AlarmRepository.java
src/main/java/com/pet/comes/repository/PinRepository.java
src/main/java/com/pet/comes/service/CustomUserDetailService.java
src/main/java/com/pet/comes/service/DiaryService.java
src/main/java/com/pet/comes/service/UserService.java
src/main/resources/application.yml

[S8] 다이어리 핀 설정하기/해제하기 API 수정

---

src/main/java/com/pet/comes/service/CommentService.java
src/main/java/com/pet/comes/service/DiaryService.java

[S7] 다이어리 댓글달기 API 수정

---

build.gradle
src/main/java/com/pet/comes/config/swagger/SwaggerConfiguration.java
src/main/java/com/pet/comes/controller/UserController.java

http://3.37.206.169:8081/swagger-ui.html

Swagger 적용

---

build.gradle
src/main/java/com/pet/comes/config/component/MapperConfiguration.java
src/main/java/com/pet/comes/controller/diary/DiaryController.java
src/main/java/com/pet/comes/dto/Rep/DiaryAllListRepDto.java
src/main/java/com/pet/comes/dto/Rep/DiaryUserDto.java
src/main/java/com/pet/comes/dto/Rep/wrapper/OrderByIdDescWrapper.java
src/main/java/com/pet/comes/model/Entity/Diary.java
src/main/java/com/pet/comes/model/Entity/Dog.java
src/main/java/com/pet/comes/model/Entity/Family.java
src/main/java/com/pet/comes/model/Entity/User.java
src/main/java/com/pet/comes/model/EnumType/SortedType.java
src/main/java/com/pet/comes/repository/CommentRepository.java
src/main/java/com/pet/comes/repository/DiaryRepository.java
src/main/java/com/pet/comes/repository/DiaryUserTestDto.java
src/main/java/com/pet/comes/repository/IDiaryUserDto.java
src/main/java/com/pet/comes/repository/OrderByIdDescWrapper.java
src/main/java/com/pet/comes/repository/UserRepository.java
src/main/java/com/pet/comes/response/ResponseMessage.java
src/main/java/com/pet/comes/service/DiaryService.java
src/main/java/com/pet/comes/service/UserService.java
src/test/java/com/pet/comes/user/UserTester.java

[S1] 인기순,최신순 정렬/조회 API 중간 commit

---

src/main/java/com/pet/comes/controller/ScheduleController.java
src/main/java/com/pet/comes/dto/Req/ScheduleDto.java
src/main/java/com/pet/comes/model/Entity/schedule/Etc.java
src/main/java/com/pet/comes/model/Entity/schedule/Schedule.java
src/main/java/com/pet/comes/response/ResponseMessage.java
src/main/java/com/pet/comes/response/Status.java
src/main/java/com/pet/comes/service/ScheduleService.java

Schedule W4

---

src/main/java/com/pet/comes/repository/schedule/AdditionalItemRepository.java
src/main/java/com/pet/comes/response/ResponseMessage.java
src/main/java/com/pet/comes/response/Status.java
src/main/java/com/pet/comes/service/ScheduleService.java

W3 수정 API 항목 13개 모두 작성 및 테스트까지 완료

Schedule W3 완성
